name: pr

on:
    pull_request:
        branches:
            - main

env:
    GIT_AUTHOR_NAME: github-actions[bot]
    GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    GIT_COMMITTER_NAME: GitHub
    GIT_COMMITTER_EMAIL: noreply@github.com
    CDK_DEFAULT_ACCOUNT: 111111111111
    CDK_DEFAULT_REGION: us-east-1
    CDK_DEPLOY_STAGES: dev int tp prod
    CDK_DEPLOY_dev_ACCOUNTS: 111111111111
    CDK_DEPLOY_int_ACCOUNTS: 111111111111
    CDK_DEPLOY_tp_ACCOUNTS: 333333333333
    CDK_DEPLOY_prod_ACCOUNTS: 333333333333
    CDK_DEPLOY_dev_111111111111_REGIONS: us-east-1
    CDK_DEPLOY_int_111111111111_REGIONS: us-east-1
    CDK_DEPLOY_tp_333333333333_REGIONS: us-east-1
    CDK_DEPLOY_prod_333333333333_REGIONS: us-east-1
